<?php

namespace App\Console\Commands;

use App\Support\Studio\SpecCatalogue;
use App\Support\Studio\SpecSchema;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

#[Signature('studio:generate {--check : Only report whether the generated files are up to date}')]
#[Description('Write the Template Spec JSON Schema and the engine catalogue from SpecCatalogue')]
class StudioGenerateCommand extends Command
{
    public function handle(Filesystem $files): int
    {
        $stale = [];

        foreach (self::outputs() as $path => $contents) {
            if ($files->exists($path) && $files->get($path) === $contents) {
                continue;
            }

            $stale[] = $path;

            if (! $this->option('check')) {
                $files->ensureDirectoryExists(dirname($path));
                $files->put($path, $contents);
            }
        }

        foreach ($stale as $path) {
            $this->components->twoColumnDetail(str_replace(base_path().'/', '', $path), $this->option('check') ? '<fg=red>stale</>' : '<fg=green>written</>');
        }

        if ($this->option('check') && $stale !== []) {
            $this->components->error('Run `php artisan studio:generate` and commit the result.');

            return self::FAILURE;
        }

        $this->components->info($stale === [] ? 'Generated files are up to date.' : 'Generated files written.');

        return self::SUCCESS;
    }

    /**
     * @return array<string, string> path => contents
     */
    public static function outputs(): array
    {
        $json = fn (array $data): string => json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);

        return [
            resource_path('studio/schema/v1.json') => $json(SpecSchema::toArray()).PHP_EOL,
            resource_path('js/templates/studio/catalogue.ts') => implode(PHP_EOL, [
                '// Generated by `php artisan studio:generate` from App\\Support\\Studio\\SpecCatalogue. Do not edit.',
                'export const studioCatalogue = '.$json(SpecCatalogue::toArray()).' as const;',
                '',
                'export type StudioCatalogue = typeof studioCatalogue;',
                '',
            ]),
        ];
    }
}
