import { useCallback } from 'react';
import { usePreferences } from '@/providers/PreferencesProvider';

const en = {
  'top.sayHi': 'Say hi',
  'top.search': 'Search',
  'dock.label': 'Quick navigation',
  'hero.hello': 'Hey, I’m',
  'hero.into': 'Into',
  'hero.seeWork': 'See the work',
  'hero.sayHi': 'Say hello',
  'hero.dragMe': 'drag me',
  'hero.localTime': 'Local time',
  'hero.statusTitle': 'Right now',
  'hero.freshTitle': 'Fresh this season',
  'hero.portrait': 'Portrait of {name}',
  'about.kicker': 'The story so far',
  'about.principles': 'House rules',
  'stack.kicker': 'Toolbox',
  'stack.title': 'Stuff I build with',
  'stack.level': 'Level {level} of 5',
  'career.kicker': 'Tickets so far',
  'career.title': 'Every stop on the ride',
  'career.previous': 'Scroll to newer roles',
  'career.next': 'Scroll to older roles',
  'career.more': 'More',
  'career.less': 'Less',
  'career.boarding': 'Boarding',
  'career.arrival': 'Arrival',
  'work.kicker': 'Selected work',
  'work.title': 'Things I shipped',
  'work.all': 'Everything',
  'clients.kicker': 'Good company',
  'clients.title': 'Teams I built with',
  'clients.intro': 'Employers and consulting clients. Every tile opens their site.',
  'clients.notes': 'Notes they left me',
  'education.kicker': 'Paperwork',
  'education.title': 'Degrees & badges',
  'writing.kicker': 'Blog',
  'writing.title': 'Things I wrote down',
  'books.kicker': 'Nightstand',
  'books.title': 'The reading pile',
  'books.pick': 'Pick a book from the pile to read my note.',
  'books.close': 'Close book',
  'books.noRating': 'Not rated yet',
  'books.pageCount': '{count} pages',
  'books.viewStack': 'Pile',
  'books.viewGrid': 'Covers',
  'books.inProgress': 'In progress',
  'contact.kicker': 'Mailbox',
  'contact.title': 'Send me a postcard',
  'contact.to': 'To',
  'contact.from': 'From',
  'contact.postmark': 'Posted from {city}',
  'contact.sentStamp': 'Delivered',
  'contact.topicLegend': 'What is it about?',
  'footer.builtWith': 'Set in Archivo, Space Grotesk and Space Mono.',
  'footer.madeWith': 'Made with stubbornness and a lot of tea.',
  'footer.top': 'Back to top',
  'page.count': '{count} total',
  'projects.cards': 'Cards',
  'projects.list': 'List',
  'case.facts': 'Quick facts',
  'case.sections': 'Jump to',
  'case.step': 'Step {index}',
  'article.stickerRead': '{count} min',
  'now.kicker': 'Status update',
  'now.where': 'Where',
  'uses.kicker': 'My kit',
  'uses.visit': 'Visit {name}',
  'notFound.kicker': 'Error 404',
  'notFound.title': 'This page wandered off.',
  'notFound.body': 'Nothing lives at this address. While you are here, drag the numbers around, then pick a way out.',
  'notFound.shuffle': 'Shuffle',
  'empty.title': 'Nothing in here.',
  'empty.body': 'Loosen the filters and try again.',
  'template.name': 'Playground',
} as const;

export type PlaygroundKey = keyof typeof en;

const ar: Record<PlaygroundKey, string> = {
  'top.sayHi': 'راسلني',
  'top.search': 'بحث',
  'dock.label': 'تنقل سريع',
  'hero.hello': 'أهلاً، أنا',
  'hero.into': 'مهووس بـ',
  'hero.seeWork': 'شوف أعمالي',
  'hero.sayHi': 'قول مرحبا',
  'hero.dragMe': 'اسحبني',
  'hero.localTime': 'الوقت عندي',
  'hero.statusTitle': 'هلأ',
  'hero.freshTitle': 'جديد هالموسم',
  'hero.portrait': 'صورة {name}',
  'about.kicker': 'القصة لحد هلأ',
  'about.principles': 'قواعد البيت',
  'stack.kicker': 'صندوق العدة',
  'stack.title': 'الأدوات يلي ببني فيها',
  'stack.level': 'المستوى {level} من 5',
  'career.kicker': 'التذاكر لحد هلأ',
  'career.title': 'كل محطة بالرحلة',
  'career.previous': 'مرر إلى الأدوار الأحدث',
  'career.next': 'مرر إلى الأدوار الأقدم',
  'career.more': 'المزيد',
  'career.less': 'أقل',
  'career.boarding': 'الإقلاع',
  'career.arrival': 'الوصول',
  'work.kicker': 'أعمال مختارة',
  'work.title': 'أشياء أطلقتها',
  'work.all': 'الكل',
  'clients.kicker': 'رفقة حلوة',
  'clients.title': 'فرق اشتغلت معها',
  'clients.intro': 'جهات عمل وعملاء استشارات. كل بطاقة بتفتح موقعهم.',
  'clients.notes': 'ملاحظات تركوها إلي',
  'education.kicker': 'الأوراق الرسمية',
  'education.title': 'شهادات وأوسمة',
  'writing.kicker': 'مدونة',
  'writing.title': 'أشياء كتبتها',
  'books.kicker': 'جنب السرير',
  'books.title': 'كومة القراءة',
  'books.pick': 'اختار كتاب من الكومة لتقرأ ملاحظتي.',
  'books.close': 'سكّر الكتاب',
  'books.noRating': 'بدون تقييم بعد',
  'books.pageCount': '{count} صفحة',
  'books.viewStack': 'كومة',
  'books.viewGrid': 'أغلفة',
  'books.inProgress': 'قيد القراءة',
  'contact.kicker': 'صندوق البريد',
  'contact.title': 'ابعتلي بطاقة بريدية',
  'contact.to': 'إلى',
  'contact.from': 'من',
  'contact.postmark': 'مرسلة من {city}',
  'contact.sentStamp': 'وصلت',
  'contact.topicLegend': 'عن شو الموضوع؟',
  'footer.builtWith': 'مكتوب بخطوط Archivo و Space Grotesk و Cairo.',
  'footer.madeWith': 'معمول بعناد وكتير شاي.',
  'footer.top': 'للأعلى',
  'page.count': '{count} بالمجمل',
  'projects.cards': 'بطاقات',
  'projects.list': 'قائمة',
  'case.facts': 'معلومات سريعة',
  'case.sections': 'انتقل إلى',
  'case.step': 'الخطوة {index}',
  'article.stickerRead': '{count} د',
  'now.kicker': 'آخر تحديث',
  'now.where': 'وين',
  'uses.kicker': 'عدتي',
  'uses.visit': 'زيارة {name}',
  'notFound.kicker': 'خطأ 404',
  'notFound.title': 'هالصفحة ضاعت.',
  'notFound.body': 'ما في شي على هالعنوان. طالما إنك هون، حرّك الأرقام شوي، وبعدين اختار طريق للرجعة.',
  'notFound.shuffle': 'خربطها',
  'empty.title': 'ما في شي هون.',
  'empty.body': 'خفف الفلاتر وجرب مرة تانية.',
  'template.name': 'ساحة اللعب',
};

const copy = { en, ar } as const;

type Variables = Record<string, string | number>;

export function usePlaygroundCopy(): (key: PlaygroundKey, variables?: Variables) => string {
  const { locale } = usePreferences();

  return useCallback(
    (key: PlaygroundKey, variables?: Variables): string => {
      const template: string = copy[locale][key];
      if (!variables) return template;
      return template.replace(/\{(\w+)\}/g, (match, name: string) => String(variables[name] ?? match));
    },
    [locale],
  );
}
