<?php

namespace App\Support\Templates;

use App\Models\StudioTemplate;
use App\Models\StudioTemplateVersion;
use App\Support\Studio\CssSanitizer;
use App\Support\Studio\StudioStyles;
use App\Support\Studio\StudioSwatch;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;
use InvalidArgumentException;

/**
 * Turns a studio template into a code template (P10-04, `php artisan template:eject`): a copy of the
 * studio engine that renders one frozen spec, for developers who want to continue in TSX. The studio
 * template itself is left untouched. See docs/12-ai-templates.md.
 */
final class TemplateEjector
{
    private const ENGINE = 'studio';

    public function __construct(
        private readonly Filesystem $files,
        private readonly TemplateScaffolder $scaffolder,
        private readonly string $templatesPath,
        private readonly string $pagesPath,
        private readonly string $screenshotsPath,
    ) {}

    /**
     * @return array{created: list<string>, updated: list<string>}
     *
     * @throws InvalidArgumentException when the id is invalid or taken, or the template has no version
     */
    public function eject(StudioTemplate $template, string $id, ?string $name = null, ?string $author = null): array
    {
        $this->scaffolder->assertNewId($id);

        $version = $template->activeVersion()->first();

        if (! $version instanceof StudioTemplateVersion) {
            throw new InvalidArgumentException("\"{$template->name}\" has no version to eject.");
        }

        $name = $name ?: $template->name;
        $templateDir = "{$this->templatesPath}/{$id}";
        $pagesDir = "{$this->pagesPath}/{$id}";
        $replacements = [
            '@/templates/'.self::ENGINE.'/' => "@/templates/{$id}/",
            "data-template='".self::ENGINE."'" => "data-template='{$id}'",
            'data-template="'.self::ENGINE.'"' => "data-template=\"{$id}\"",
            'StudioLayout' => Str::studly($id).'Layout',
        ];

        // 1. The engine, renamed.
        $this->files->copyDirectory("{$this->templatesPath}/".self::ENGINE, $templateDir);

        foreach ($this->files->allFiles($templateDir) as $file) {
            $path = $file->getPathname();
            $renamed = str_replace('StudioLayout', Str::studly($id).'Layout', $path);

            $this->files->put($renamed, strtr($file->getContents(), $replacements));

            if ($renamed !== $path) {
                $this->files->delete($path);
            }
        }

        $this->files->ensureDirectoryExists($pagesDir);

        foreach ($this->files->files("{$this->pagesPath}/".self::ENGINE) as $file) {
            $contents = strtr($file->getContents(), $replacements);
            $contents = str_replace('// Inertia page of the studio engine: renders any studio template from its spec (docs/12-ai-templates.md §3).', "// Inertia page of the {$name} template (ejected from a studio template).", $contents);
            $this->files->put("{$pagesDir}/{$file->getFilename()}", $contents);
        }

        // 2. The frozen spec, and the hook that reads it instead of the shared `studio` prop.
        $this->files->put("{$templateDir}/frozenSpec.ts", $this->frozenSpec($template, $version));
        $this->files->put("{$templateDir}/useSpec.ts", $this->useSpec($name));
        $this->files->put("{$templateDir}/catalogue.ts", str_replace(
            '// Generated by `php artisan studio:generate` from App\Support\Studio\SpecCatalogue. Do not edit.',
            '// Copied from the studio engine when this template was ejected: what a spec could contain then.',
            $this->files->get("{$templateDir}/catalogue.ts"),
        ));

        // 3. Tokens and the spec's (sanitised) CSS, after the engine's base styles.
        $tokens = str_replace(CssSanitizer::SCOPE, "[data-template=\"{$id}\"]", StudioStyles::render($version->spec));
        $this->files->append("{$templateDir}/styles.css", "\n/* Design tokens and CSS of the spec, frozen by template:eject. */\n{$tokens}\n");

        // 4. Manifest, screenshot, README, stylesheet import.
        $screenshot = $this->screenshot($template, $version, $id);
        $manifest = [
            'id' => $id,
            'name' => $name,
            'description' => $template->description ?: "Ejected from the studio template {$template->name}.",
            ...($author ? ['author' => $author] : []),
            'preloadFonts' => TemplateDefinition::forStudio($template->setRelation('activeVersion', $version))->preloadFonts,
            'screenshot' => 'templates/'.basename($screenshot),
        ];
        $this->files->put("{$templateDir}/template.json", json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE).PHP_EOL);
        $this->files->put("{$templateDir}/README.md", $this->readme($name, $id, $template, $version));

        $this->scaffolder->importStylesheet(self::ENGINE, $id);

        return ['created' => [$templateDir, $pagesDir, $screenshot], 'updated' => [config('portfolio.templates.stylesheet')]];
    }

    private function frozenSpec(StudioTemplate $template, StudioTemplateVersion $version): string
    {
        $json = json_encode($version->spec, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        return <<<TS
            // The design this template renders: version {$version->number} of the studio template "{$template->name}",
            // frozen by `php artisan template:eject`. Change it here, or change the components directly.
            import type { TemplateSpec } from './spec';

            export const spec: TemplateSpec = {$json};

            TS;
    }

    private function useSpec(string $name): string
    {
        return <<<TS
            import { useCallback } from 'react';
            import { spec } from './frozenSpec';
            import type { CopyKey, TemplateSpec } from './spec';

            /**
             * The design of the {$name} template (frozenSpec.ts). In the studio engine this came from the
             * shared `studio` prop; an ejected template carries its own.
             */
            export function useStudioSpec(): TemplateSpec {
                return spec;
            }

            /** UI copy from the spec (`copy.<key>`), or the fallback. */
            export function useCopy(): (key: CopyKey, fallback: string) => string {
                const { copy } = useStudioSpec();

                return useCallback(
                    (key: CopyKey, fallback: string) => copy?.[key] ?? fallback,
                    [copy],
                );
            }

            TS;
    }

    /**
     * The studio template's screenshot when it has one, otherwise its swatch.
     */
    private function screenshot(StudioTemplate $template, StudioTemplateVersion $version, string $id): string
    {
        $this->files->ensureDirectoryExists($this->screenshotsPath);
        $media = $template->getFirstMedia('screenshot');

        if ($media !== null && is_file($media->getPath())) {
            $path = "{$this->screenshotsPath}/{$id}.".strtolower(pathinfo($media->getPath(), PATHINFO_EXTENSION) ?: 'png');
            $this->files->copy($media->getPath(), $path);

            return $path;
        }

        $path = "{$this->screenshotsPath}/{$id}.svg";
        $this->files->put($path, StudioSwatch::svg($version->spec));

        return $path;
    }

    private function readme(string $name, string $id, StudioTemplate $template, StudioTemplateVersion $version): string
    {
        return <<<MD
            # {$name}

            Ejected from version {$version->number} of the studio template "{$template->name}" with
            `php artisan template:eject`. It is a copy of the studio engine that renders one frozen spec, and
            it is yours now: nothing here is regenerated.

            - `frozenSpec.ts`: the design (tokens, layout, sections and variants, copy). Change it to try
              other sections or variants; the types in `spec.ts` keep it valid.
            - `styles.css`: the engine's base styles, then the spec's tokens and CSS (at the end).
            - `home/`, `sections/`, `pages/`, `components/`, `layout/`: the markup. Change anything; remove
              the variants you do not use.
            - Behaviour (contact form, filters, search, theme, article blocks) comes from `@/kit`.

            Next steps:

            1. Run `composer dev` and preview it at `/?template={$id}` while signed in to the panel.
            2. Replace the screenshot in `public/templates/` (960 × 600) and update `template.json`.
            3. Run `composer ci:check`: every page of the template is tested automatically.

            Guide: docs/templates/building-a-template.md.

            MD;
    }
}
