import { useCallback } from 'react';
import { usePreferences } from '@/providers/PreferencesProvider';

const en = {
  'nav.about': 'About me',
  'nav.resume': 'Resume',
  'nav.services': 'Services',
  'nav.portfolio': 'Portfolio',
  'nav.blog': 'Blog',
  'nav.contact': 'Contact',
  'nav.pages': 'Pages',
  'nav.social': 'Social',
  'nav.search': 'Search',
  'menu.title': 'Get in touch',
  'menu.email': 'Email',
  'menu.location': 'Location',
  'menu.localTime': 'Local time',
  'menu.availability': 'Availability',
  'hero.hello': 'Hey, I’m {name}',
  'hero.stack': 'Hands-on with',
  'hero.and': 'and',
  'hero.more': '...and more',
  'hero.cta': '[ Say hello ]',
  'hero.portrait': 'Portrait of {name}',
  'coop.kicker': 'Cooperation',
  'coop.titleA': 'More than +{count}',
  'coop.titleB': 'teams',
  'coop.titleC': 'trusted',
  'coop.titleD': 'my work_',
  'coop.email': 'email',
  'coop.based': 'based',
  'coop.status': 'status',
  'journal.kicker': 'Git Journaling',
  'services.kicker': 'Services',
  'services.titleA': 'Building systems',
  'services.titleB': 'that stay calm',
  'services.titleC': 'under real-world load',
  'services.reach': 'Reach out!',
  'services.working': 'Working daily with',
  'experience.kicker': 'Experience',
  'experience.titleA': '+{count}',
  'experience.titleB': 'years of',
  'experience.titleC': 'passion',
  'experience.titleD': 'for',
  'experience.titleE': 'shipping calm software',
  'experience.present': 'Present',
  'experience.companies': 'Companies',
  'resume.education': 'Education',
  'resume.certifications': 'Certifications',
  'resume.verify': 'Verify credential',
  'projects.kicker': 'Projects',
  'projects.title': 'My Recent Works',
  'projects.info': 'Project Info',
  'projects.client': 'Client',
  'projects.time': 'Completion Time',
  'projects.tech': 'Technologies',
  'projects.case': 'Read case study',
  'projects.previous': 'Previous project',
  'projects.next': 'Next project',
  'projects.slide': 'Project {current} of {total}',
  'skills.kicker': 'Skills',
  'skills.title': 'My Skills',
  'blog.kicker': 'Latest Posts',
  'blog.title': 'From Blog',
  'blog.all': 'Browse every article',
  'contact.title': 'Let’s connect',
  'contact.subject': 'Subject',
  'contact.sendArrow': 'Send Message',
  'footer.top': 'Back to top',
  'footer.madeWith': 'Set in DM Mono.',
  'page.count': '{count} total',
  'case.info': 'Project info',
  'now.kicker': 'Status update',
  'uses.kicker': 'My setup',
  'books.kicker': 'Reading list',
  'books.pick': 'Select a book to read my note.',
  'books.close': 'Close',
  'books.noRating': 'Not rated yet',
  'notFound.kicker': 'Error 404',
  'notFound.cmd': 'cd {path}',
  'notFound.out': 'bash: cd: no such file or directory',
  'template.name': 'Terminal',
} as const;

export type TerminalKey = keyof typeof en;

const ar: Record<TerminalKey, string> = {
  'nav.about': 'عني',
  'nav.resume': 'السيرة',
  'nav.services': 'الخدمات',
  'nav.portfolio': 'الأعمال',
  'nav.blog': 'المدونة',
  'nav.contact': 'تواصل',
  'nav.pages': 'الصفحات',
  'nav.social': 'حساباتي',
  'nav.search': 'بحث',
  'menu.title': 'خلّينا نحكي',
  'menu.email': 'البريد',
  'menu.location': 'الموقع',
  'menu.localTime': 'الوقت عندي',
  'menu.availability': 'التوفر',
  'hero.hello': 'أهلاً، أنا {name}',
  'hero.stack': 'بشتغل يومياً بـ',
  'hero.and': 'و',
  'hero.more': '...وغيرها',
  'hero.cta': '[ قول مرحبا ]',
  'hero.portrait': 'صورة {name}',
  'coop.kicker': 'تعاون',
  'coop.titleA': 'أكتر من +{count}',
  'coop.titleB': 'فرق',
  'coop.titleC': 'وثقت',
  'coop.titleD': 'بشغلي_',
  'coop.email': 'بريد',
  'coop.based': 'مقيم',
  'coop.status': 'حالة',
  'journal.kicker': 'سجل Git',
  'services.kicker': 'الخدمات',
  'services.titleA': 'بناء أنظمة',
  'services.titleB': 'بتضل هادية',
  'services.titleC': 'تحت الضغط الحقيقي',
  'services.reach': 'راسلني!',
  'services.working': 'بشتغل يومياً مع',
  'experience.kicker': 'الخبرة',
  'experience.titleA': '+{count}',
  'experience.titleB': 'سنين من',
  'experience.titleC': 'الشغف',
  'experience.titleD': 'في',
  'experience.titleE': 'بناء برمجيات هادية',
  'experience.present': 'حالياً',
  'experience.companies': 'الشركات',
  'resume.education': 'التعليم',
  'resume.certifications': 'الشهادات',
  'resume.verify': 'تحقق من الشهادة',
  'projects.kicker': 'المشاريع',
  'projects.title': 'آخر أعمالي',
  'projects.info': 'معلومات المشروع',
  'projects.client': 'العميل',
  'projects.time': 'المدة',
  'projects.tech': 'التقنيات',
  'projects.case': 'اقرأ دراسة الحالة',
  'projects.previous': 'المشروع السابق',
  'projects.next': 'المشروع التالي',
  'projects.slide': 'المشروع {current} من {total}',
  'skills.kicker': 'المهارات',
  'skills.title': 'مهاراتي',
  'blog.kicker': 'آخر المقالات',
  'blog.title': 'من المدونة',
  'blog.all': 'تصفح كل المقالات',
  'contact.title': 'خلّينا نتواصل',
  'contact.subject': 'الموضوع',
  'contact.sendArrow': 'أرسل الرسالة',
  'footer.top': 'للأعلى',
  'footer.madeWith': 'مكتوب بخط DM Mono و IBM Plex Sans Arabic.',
  'page.count': '{count} بالمجمل',
  'case.info': 'معلومات المشروع',
  'now.kicker': 'آخر تحديث',
  'uses.kicker': 'عدتي',
  'books.kicker': 'قائمة القراءة',
  'books.pick': 'اختار كتاب لتقرأ ملاحظتي عليه.',
  'books.close': 'إغلاق',
  'books.noRating': 'بدون تقييم بعد',
  'notFound.kicker': 'خطأ 404',
  'notFound.cmd': 'cd {path}',
  'notFound.out': 'bash: cd: no such file or directory',
  'template.name': 'الطرفية',
};

const copy = { en, ar } as const;

type Variables = Record<string, string | number>;

export function useTerminalCopy(): (key: TerminalKey, variables?: Variables) => string {
  const { locale } = usePreferences();

  return useCallback(
    (key: TerminalKey, variables?: Variables): string => {
      const template: string = copy[locale][key];
      if (!variables) return template;
      return template.replace(/\{(\w+)\}/g, (match, name: string) => String(variables[name] ?? match));
    },
    [locale],
  );
}
