// Generated by `php artisan studio:generate` from App\Support\Studio\SpecCatalogue. Do not edit.
export const studioCatalogue = {
    "version": "studio/v1",
    "colorRoles": [
        "bg",
        "surface",
        "text",
        "muted",
        "accent",
        "border"
    ],
    "fonts": {
        "geist": {
            "label": "Geist",
            "family": "'Geist Variable', 'Geist', ui-sans-serif, system-ui, sans-serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "bricolage-grotesque": {
            "label": "Bricolage Grotesque",
            "family": "'Bricolage Grotesque Variable', 'Bricolage Grotesque', ui-sans-serif, system-ui, sans-serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "space-grotesk": {
            "label": "Space Grotesk",
            "family": "'Space Grotesk Variable', 'Space Grotesk', ui-sans-serif, system-ui, sans-serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "archivo": {
            "label": "Archivo",
            "family": "'Archivo Variable', 'Archivo', ui-sans-serif, system-ui, sans-serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "jetbrains-mono": {
            "label": "JetBrains Mono",
            "family": "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, 'SFMono-Regular', monospace",
            "kinds": [
                "display",
                "body",
                "mono"
            ]
        },
        "space-mono": {
            "label": "Space Mono",
            "family": "'Space Mono', ui-monospace, 'SFMono-Regular', monospace",
            "kinds": [
                "display",
                "body",
                "mono"
            ]
        },
        "dm-mono": {
            "label": "DM Mono",
            "family": "'DM Mono', ui-monospace, monospace",
            "kinds": [
                "display",
                "body",
                "mono"
            ]
        },
        "system-sans": {
            "label": "System sans-serif",
            "family": "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "system-serif": {
            "label": "System serif",
            "family": "ui-serif, Georgia, 'Times New Roman', serif",
            "kinds": [
                "display",
                "body"
            ]
        },
        "system-mono": {
            "label": "System monospace",
            "family": "ui-monospace, 'SFMono-Regular', Menlo, monospace",
            "kinds": [
                "display",
                "body",
                "mono"
            ]
        }
    },
    "tokens": {
        "radius": [
            "none",
            "sm",
            "md",
            "lg",
            "full"
        ],
        "density": [
            "compact",
            "comfortable",
            "airy"
        ],
        "shadow": [
            "none",
            "soft",
            "hard"
        ],
        "motion": [
            "none",
            "subtle",
            "lively"
        ]
    },
    "layout": {
        "header": [
            "bar-sticky",
            "floating-pill",
            "sidebar",
            "minimal"
        ],
        "footer": [
            "minimal",
            "columns",
            "big-name"
        ]
    },
    "containers": [
        "narrow",
        "default",
        "wide"
    ],
    "homeSections": {
        "hero": {
            "variants": [
                "centered",
                "split-portrait",
                "editorial",
                "terminal"
            ],
            "props": {
                "showAvailability": {
                    "type": "boolean"
                },
                "showSocials": {
                    "type": "boolean"
                }
            }
        },
        "about": {
            "variants": [
                "prose",
                "columns"
            ],
            "props": {}
        },
        "stats": {
            "variants": [
                "inline",
                "cards"
            ],
            "props": {}
        },
        "skills": {
            "variants": [
                "chips",
                "grid",
                "bars"
            ],
            "props": {}
        },
        "career": {
            "variants": [
                "timeline",
                "cards",
                "table"
            ],
            "props": {
                "limit": {
                    "type": "integer",
                    "min": 1,
                    "max": 20
                }
            }
        },
        "projects": {
            "variants": [
                "grid",
                "bento",
                "list",
                "slider"
            ],
            "props": {
                "limit": {
                    "type": "integer",
                    "min": 1,
                    "max": 12
                }
            }
        },
        "clients": {
            "variants": [
                "logos",
                "marquee"
            ],
            "props": {}
        },
        "testimonials": {
            "variants": [
                "carousel",
                "wall"
            ],
            "props": {}
        },
        "education": {
            "variants": [
                "list",
                "cards"
            ],
            "props": {}
        },
        "writing": {
            "variants": [
                "list",
                "cards"
            ],
            "props": {
                "limit": {
                    "type": "integer",
                    "min": 1,
                    "max": 12
                }
            }
        },
        "books": {
            "variants": [
                "shelf",
                "covers"
            ],
            "props": {
                "limit": {
                    "type": "integer",
                    "min": 1,
                    "max": 24
                }
            }
        },
        "contact": {
            "variants": [
                "card",
                "split",
                "minimal"
            ],
            "props": {}
        }
    },
    "pages": {
        "projects": [
            "grid",
            "list",
            "table"
        ],
        "caseStudy": [
            "longform",
            "sidebar"
        ],
        "writing": [
            "list",
            "cards"
        ],
        "article": [
            "centered",
            "wide"
        ],
        "books": [
            "shelf",
            "grid"
        ],
        "uses": [
            "columns",
            "list"
        ],
        "now": [
            "notes",
            "timeline"
        ],
        "notFound": [
            "big-number",
            "minimal"
        ]
    },
    "copy": {
        "heroKicker": 60,
        "heroCta": 30,
        "aboutHeading": 60,
        "skillsHeading": 60,
        "careerHeading": 60,
        "projectsHeading": 60,
        "clientsHeading": 60,
        "testimonialsHeading": 60,
        "educationHeading": 60,
        "writingHeading": 60,
        "booksHeading": 60,
        "contactHeading": 80,
        "contactIntro": 200,
        "footerNote": 120
    },
    "limits": {
        "name": 60,
        "homeSections": 16,
        "css": 40960
    }
} as const;

export type StudioCatalogue = typeof studioCatalogue;
