import { useCallback } from 'react';
import { interpolate } from '@/hooks/useTranslation';

const en = {
    'nav.about': 'About me',
    'nav.resume': 'Resume',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.pages': 'Pages',
    'nav.social': 'Social',
    'nav.search': 'Search',
    'menu.title': 'Get in touch',
    'menu.email': 'Email',
    'menu.location': 'Location',
    'menu.localTime': 'Local time',
    'menu.availability': 'Availability',
    'hero.hello': 'Hey, I’m {name}',
    'hero.stack': 'Hands-on with',
    'hero.and': 'and',
    'hero.more': '...and more',
    'hero.cta': '[ Say hello ]',
    'hero.portrait': 'Portrait of {name}',
    'coop.kicker': 'Cooperation',
    'coop.titleA': 'More than +{count}',
    'coop.titleB': 'teams',
    'coop.titleC': 'trusted',
    'coop.titleD': 'my work_',
    'coop.email': 'email',
    'coop.based': 'based',
    'coop.status': 'status',
    'journal.kicker': 'Git Journaling',
    'services.kicker': 'Services',
    'services.titleA': 'Building systems',
    'services.titleB': 'that stay calm',
    'services.titleC': 'under real-world load',
    'services.reach': 'Reach out!',
    'experience.kicker': 'Experience',
    'experience.titleA': '+{count}',
    'experience.titleB': 'years of',
    'experience.titleC': 'passion',
    'experience.titleD': 'for',
    'experience.titleE': 'shipping calm software',
    'experience.present': 'Present',
    'experience.companies': 'Companies',
    'experience.showAchievements': 'View achievements',
    'experience.hideAchievements': 'Hide achievements',
    'resume.education': 'Education',
    'resume.certifications': 'Certifications',
    'resume.verify': 'Verify credential',
    'projects.kicker': 'Projects',
    'projects.title': 'My Recent Works',
    'projects.info': 'Project Info',
    'projects.client': 'Client',
    'projects.time': 'Completion Time',
    'projects.tech': 'Technologies',
    'projects.case': 'Read case study',
    'projects.previous': 'Previous project',
    'projects.next': 'Next project',
    'projects.slide': 'Project {current} of {total}',
    'skills.kicker': 'Skills',
    'skills.title': 'My Skills',
    'blog.kicker': 'Latest Posts',
    'blog.title': 'From Blog',
    'blog.all': 'Browse every article',
    'contact.title': 'Let’s connect',
    'contact.subject': 'Subject',
    'contact.sendArrow': 'Send Message',
    'footer.top': 'Back to top',
    'footer.madeWith': 'Set in DM Mono.',
    'page.count': '{count} total',
    'case.info': 'Project info',
    'now.kicker': 'Status update',
    'uses.kicker': 'My setup',
    'books.kicker': 'Reading list',
    'books.pick': 'Select a book to read my note.',
    'books.close': 'Close',
    'books.noRating': 'Not rated yet',
    'notFound.kicker': 'Error 404',
    'notFound.cmd': 'cd {path}',
    'notFound.out': 'bash: cd: no such file or directory',
    'template.name': 'Terminal',
} as const;

export type TerminalKey = keyof typeof en;

const copy = { en } as const;

type Variables = Record<string, string | number>;

export function useTerminalCopy(): (
    key: TerminalKey,
    variables?: Variables,
) => string {
    return useCallback(
        (key: TerminalKey, variables?: Variables): string =>
            interpolate(copy.en[key], variables),
        [],
    );
}
